version: '3'
services:
  # MSSQL Server
  mssql-server:
    image: mssqlserver
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    ports:
      - 1434:1433
    volumes:
      - mssqldata:/var/opt/mssql
  
volumes:
  mssqldata:
    driver: local